# Generated by Django 5.2.8 on 2026-05-26 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='devicecar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('device_amount', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='reservationlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time_id', models.IntegerField()),
                ('device_id', models.IntegerField()),
                ('devicecar_id', models.IntegerField()),
            ],
            options={
                'db_table': 'show_reservationlist',
            },
        ),
        migrations.CreateModel(
            name='Borrowlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25, verbose_name='聯絡電話')),
                ('location', models.CharField(max_length=10, verbose_name='教室')),
                ('usage_type', models.CharField(choices=[('once', '單次'), ('weekly', '每周')], default='once', max_length=10)),
                ('device_type', models.CharField(choices=[('ipad', 'iPad'), ('chromebook', 'Chromebook'), ('surface_go', 'Surface Go'), ('acer_laptop', 'Acer 小筆電')], max_length=20, verbose_name='載具種類')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='結束日期')),
                ('day', models.CharField(blank=True, choices=[('Monday', '星期一'), ('Tuesday', '星期二'), ('Wednesday', '星期三'), ('Thursday', '星期四'), ('Friday', '星期五')], max_length=50, null=True, verbose_name='星期')),
                ('periods', models.CharField(choices=[('1', '第一節'), ('2', '第二節'), ('3', '第三節'), ('4', '第四節'), ('4.5', '午休'), ('5', '第五節'), ('6', '第六節'), ('7', '第七節'), ('8', '第八節')], default='1', max_length=50, verbose_name='預約節次')),
                ('device_id', models.CharField(default='', max_length=10, verbose_name='載具編號')),
                ('time_id', models.CharField(default='', max_length=10, verbose_name='時間')),
                ('status', models.CharField(choices=[('待審核', '待審核'), ('已通過', '已通過'), ('已拒絕', '已拒絕')], default='待審核', max_length=10, verbose_name='審核狀態')),
                ('device_amount', models.PositiveIntegerField(default=1)),
                ('classroom', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='借用老師')),
            ],
        ),
    ]
