# Generated by Django 5.2.7 on 2026-05-21 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='借用人')),
                ('phone', models.CharField(max_length=25, verbose_name='連絡電話')),
                ('usage_type', models.CharField(choices=[('once', '單次'), ('weekly', '每周')], default='once', max_length=10)),
                ('device_id', models.IntegerField()),
                ('device_amount', models.PositiveIntegerField(choices=[('1', '1台'), ('2', '2台'), ('3', '3台'), ('4', '4台'), ('5', '5台'), ('6', '6台'), ('7', '7台'), ('8', '8台'), ('9', '9台'), ('10', '10台'), ('11', '11台'), ('12', '12台'), ('13', '13台'), ('14', '14台'), ('15', '15台'), ('16', '16台'), ('17', '17台'), ('18', '18台'), ('19', '19台'), ('20', '20台'), ('21', '21台'), ('22', '22台'), ('23', '23台'), ('24', '24台'), ('25', '25台'), ('26', '26台'), ('27', '27台'), ('28', '28台'), ('29', '29台'), ('30', '30台'), ('31', '31台'), ('32', '32台'), ('33', '33台'), ('34', '34台'), ('35', '35台'), ('one', '1車'), ('two', '2車'), ('three', '3車'), ('four', '4車'), ('five', '5車')], default=1)),
                ('time_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[], default='', max_length=10)),
                ('amount', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='devicecar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('device_amount', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='結束日期')),
                ('periods', models.CharField(choices=[('1', '第一節'), ('2', '第二節'), ('3', '第三節'), ('4', '第四節'), ('5', '第五節'), ('6', '第六節'), ('7', '第七節'), ('8', '第八節'), ('4.5', '午休')], max_length=50, verbose_name='節次')),
                ('day', models.CharField(choices=[('Monday', '星期一'), ('Tuesday', '星期二'), ('Wednesday', '星期三'), ('Thursday', '星期四'), ('Friday', '星期五')], max_length=50, verbose_name='星期')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('email', models.CharField(max_length=100, verbose_name='信箱')),
                ('role', models.CharField(choices=[('teacher', '老師'), ('student', '學生')], default='student', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='reservationlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('periods', models.CharField(max_length=20)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('borrow_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.borrowlist')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.user')),
            ],
        ),
    ]

# Generated by Django 5.2.8 on 2026-05-21 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('ipad', 'iPad'), ('chromebook', 'Chromebook'), ('surface_go', 'Surface Go'), ('acer_laptop', 'Acer 小筆電')], max_length=20, unique=True, verbose_name='載具種類')),
            ],
        ),
        migrations.CreateModel(
            name='devicecar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_code', models.CharField(help_text='例如: B車', max_length=10, verbose_name='車次代號')),
                ('capacity', models.PositiveIntegerField(default=42, verbose_name='車內載具總台數')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.device', verbose_name='所屬載具種類')),
            ],
        ),
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25, verbose_name='聯絡電話')),
                ('location', models.CharField(max_length=10, verbose_name='教室')),
                ('usage_type', models.CharField(choices=[('once', '單次'), ('weekly', '每周')], default='once', max_length=10)),
                ('device_id', models.IntegerField()),
                ('device_amount', models.PositiveIntegerField(choices=[('1', '1台'), ('2', '2台'), ('3', '3台'), ('4', '4台'), ('5', '5台'), ('6', '6台'), ('7', '7台'), ('8', '8台'), ('9', '9台'), ('10', '10台'), ('11', '11台'), ('12', '12台'), ('13', '13台'), ('14', '14台'), ('15', '15台'), ('16', '16台'), ('17', '17台'), ('18', '18台'), ('19', '19台'), ('20', '20台'), ('21', '21台'), ('22', '22台'), ('23', '23台'), ('24', '24台'), ('25', '25台'), ('26', '26台'), ('27', '27台'), ('28', '28台'), ('29', '29台'), ('30', '30台'), ('31', '31台'), ('32', '32台'), ('33', '33台'), ('34', '34台'), ('35', '35台'), ('one', '1車'), ('two', '2車'), ('three', '3車'), ('four', '4車'), ('five', '5車')], default=1)),
                ('classroom', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='借用老師')),
            ],
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1', '第一節'), ('2', '第二節'), ('3', '第三節'), ('4', '第四節'), ('5', '第五節'), ('6', '第六節'), ('7', '第七節'), ('8', '第八節'), ('4.5', '午休')], max_length=5, verbose_name='借用節次')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('end_date', models.DateField(help_text='若是單次借用，結束日期請設定與開始日期相同', verbose_name='結束日期')),
                ('excluded_weeks', models.CharField(blank=True, help_text='例如：第9週期中考、2026-05-20', max_length=200, null=True, verbose_name='不包含的週次/日期')),
                ('borrow_type', models.CharField(choices=[('unit', '散借 (20台以內)'), ('car', '借用整台載具車')], default='unit', max_length=10, verbose_name='借用形式')),
                ('quantity', models.PositiveIntegerField(help_text='散借填寫台數，車借填寫車數', verbose_name='借用數量')),
                ('pickup_by', models.CharField(default='學生（帶學生證）', max_length=50, verbose_name='誰來拿')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='填單時間')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.device', verbose_name='要借什麼載具')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='借用當天日期')),
                ('period', models.CharField(choices=[('1', '第一節'), ('2', '第二節'), ('3', '第三節'), ('4', '第四節'), ('5', '第五節'), ('6', '第六節'), ('7', '第七節'), ('8', '第八節'), ('4.5', '午休')], max_length=5, verbose_name='節次')),
                ('is_scattered', models.BooleanField(default=False, verbose_name='是否為散借')),
                ('borrowed_amount', models.PositiveIntegerField(verbose_name='實際借出載具數量')),
                ('assigned_car', models.ForeignKey(blank=True, help_text='若為散借則此處留空', null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.devicecar', verbose_name='指派車次')),
                ('booking_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.list', verbose_name='對應的表單')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.device', verbose_name='載具種類')),
            ],
            options={
                'verbose_name': '預約總表',
                'unique_together': {('date', 'period', 'assigned_car')},
            },
        ),
    ]
