# Generated by Django 5.2.8 on 2026-05-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.CharField(max_length=20, verbose_name='借用老師'),
        ),
    ]
