# Generated by Django 5.2.8 on 2026-05-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowlist',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='借用老師'),
        ),
    ]
