# Generated by Django 5.2.7 on 2026-05-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowlist',
            name='day',
            field=models.CharField(blank=True, choices=[('Monday', '星期一'), ('Tuesday', '星期二'), ('Wednesday', '星期三'), ('Thursday', '星期四'), ('Friday', '星期五')], max_length=50, null=True, verbose_name='星期'),
        ),
        migrations.AddField(
            model_name='borrowlist',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='結束日期'),
        ),
        migrations.AddField(
            model_name='borrowlist',
            name='periods',
            field=models.CharField(choices=[('1', '第一節'), ('2', '第二節'), ('3', '第三節'), ('4', '第四節'), ('4.5', '午休'), ('5', '第五節'), ('6', '第六節'), ('7', '第七節'), ('8', '第八節')], default='1', max_length=50, verbose_name='預約節次'),
        ),
        migrations.AddField(
            model_name='borrowlist',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日期'),
        ),
    ]
