# Generated by Django 5.2.7 on 2026-05-22 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowlist',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.device', verbose_name='設備ID'),
        ),
        migrations.AlterField(
            model_name='borrowlist',
            name='time_id',
            field=models.CharField(default='1', max_length=20, verbose_name='時間ID'),
        ),
        migrations.AlterField(
            model_name='borrowlist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='借用人'),
        ),
    ]
