# Generated by Django 5.2.8 on 2026-05-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_alter_borrowlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowlist',
            name='periods_end',
            field=models.CharField(choices=[('1', '第一節'), ('2', '第二節'), ('3', '第三節'), ('4', '第四節'), ('4.5', '午休'), ('5', '第五節'), ('6', '第六節'), ('7', '第七節'), ('8', '第八節')], default='1', max_length=50, verbose_name='結束預約節次'),
        ),
        migrations.AlterField(
            model_name='borrowlist',
            name='periods',
            field=models.CharField(choices=[('1', '第一節'), ('2', '第二節'), ('3', '第三節'), ('4', '第四節'), ('4.5', '午休'), ('5', '第五節'), ('6', '第六節'), ('7', '第七節'), ('8', '第八節')], default='1', max_length=50, verbose_name='開始預約節次'),
        ),
    ]
