# Generated by Django 5.2.7 on 2026-05-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_alter_borrowlist_device_id_alter_borrowlist_time_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowlist',
            name='device_id',
            field=models.CharField(default='1', max_length=50, verbose_name='設備ID'),
        ),
    ]
