# Generated by Django 6.0.5 on 2026-05-22 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_alter_list_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='借用老師')),
                ('phone', models.CharField(max_length=25, verbose_name='聯絡電話')),
                ('location', models.CharField(max_length=10, verbose_name='教室')),
                ('usage_type', models.CharField(choices=[('once', '單次'), ('weekly', '每周')], default='once', max_length=10)),
                ('device_id', models.IntegerField()),
                ('device_amount', models.PositiveIntegerField(choices=[('1', '1台'), ('2', '2台'), ('3', '3台'), ('4', '4台'), ('5', '5台'), ('6', '6台'), ('7', '7台'), ('8', '8台'), ('9', '9台'), ('10', '10台'), ('11', '11台'), ('12', '12台'), ('13', '13台'), ('14', '14台'), ('15', '15台'), ('16', '16台'), ('17', '17台'), ('18', '18台'), ('19', '19台'), ('20', '20台'), ('21', '21台'), ('22', '22台'), ('23', '23台'), ('24', '24台'), ('25', '25台'), ('26', '26台'), ('27', '27台'), ('28', '28台'), ('29', '29台'), ('30', '30台'), ('31', '31台'), ('32', '32台'), ('33', '33台'), ('34', '34台'), ('35', '35台'), ('one', '1車'), ('two', '2車'), ('three', '3車'), ('four', '4車'), ('five', '5車')], default=1)),
                ('time_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='reservationschedule',
            name='booking_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.borrowlist', verbose_name='對應的表單'),
        ),
        migrations.DeleteModel(
            name='list',
        ),
    ]
