# Generated by Django 5.2.7 on 2026-05-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_alter_borrowlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowlist',
            name='exclude_weeks',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='排除週次/備註'),
        ),
    ]
