# Generated by Django 5.2.10 on 2026-05-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_borrowlist_exclude_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecar',
            name='device_type',
            field=models.CharField(blank=True, choices=[('ipad', 'iPad'), ('chromebook', 'Chromebook'), ('surface_go', 'Surface Go'), ('acer_laptop', 'Acer 小筆電')], max_length=20, verbose_name='載具種類'),
        ),
    ]
