# Generated by Django 5.2.8 on 2026-05-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_borrowlist_periods_end_alter_borrowlist_periods'),
        ('show', '0004_devicecar_device_type'),
    ]

    operations = [
    ]
