# Generated by Django 5.2.7 on 2026-05-22 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_borrowlist_quantity_alter_borrowlist_device_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowlist',
            name='device_amount',
        ),
    ]
