# Generated by Django 5.2.8 on 2026-05-31 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_merge_20260528_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='載具車名稱/編號')),
                ('total_devices', models.IntegerField(default=40, verbose_name='這台車的載具總台數')),
            ],
            options={
                'verbose_name': '行動載具車管理',
                'verbose_name_plural': '行動載具車管理',
            },
        ),
        migrations.AddField(
            model_name='borrowlist',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.devicevehicle', verbose_name='系統指派載具車'),
        ),
    ]
