# Generated by Django 5.2.10 on 2026-05-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_borrowlist_alter_reservationschedule_booking_form_and_more'),
        ('show', '0005_remove_borrowlist_device_amount'),
    ]

    operations = [
    ]
