# Generated by Django 5.2.8 on 2026-05-31 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_devicevehicle_borrowlist_assigned_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowlist',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.devicecar', verbose_name='系統指派載具車'),
        ),
        migrations.DeleteModel(
            name='DeviceVehicle',
        ),
    ]
